name: Lint
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v3
        with:
          version: 'latest'

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies 📦
        run: |
          pnpm install

      - name: Lint 🧹
        run: |
          pnpm lint
          pnpm lint:styles
