name: Lint
on:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update npm 📦
        run: npm install -g npm@latest

      - name: Install dependencies 📦
        run: |
          npm ci

      - name: Lint 🧹
        run: |
          npm run lint
